using System.Globalization;
using System.Text;

namespace DLNACast.Core.MiPlay;

public sealed record MiPlayRtspHeader(string Name, string Value);

/// <summary>
/// Offline encoder for the RTSP/1.0 responses used by Xiaomi's media回连 path.
/// It only formats bytes; it does not listen on sockets or send media/control data.
/// </summary>
public static class MiPlayRtspResponseCodec
{
    public static byte[] EncodeOk(int cseq, IEnumerable<MiPlayRtspHeader>? headers = null) =>
        Encode(200, "OK", cseq, headers, []);

    public static byte[] EncodeOk(int cseq, ReadOnlySpan<byte> body, IEnumerable<MiPlayRtspHeader>? headers = null) =>
        Encode(200, "OK", cseq, headers, body);

    public static byte[] Encode(
        int statusCode,
        string reasonPhrase,
        int cseq,
        IEnumerable<MiPlayRtspHeader>? headers,
        ReadOnlySpan<byte> body)
    {
        if (statusCode is < 100 or > 999)
        {
            throw new ArgumentOutOfRangeException(nameof(statusCode));
        }
        ArgumentException.ThrowIfNullOrWhiteSpace(reasonPhrase);
        if (reasonPhrase.Contains('\r', StringComparison.Ordinal) ||
            reasonPhrase.Contains('\n', StringComparison.Ordinal))
        {
            throw new ArgumentException("The RTSP reason phrase must be a single line.", nameof(reasonPhrase));
        }
        if (cseq < 0)
        {
            throw new ArgumentOutOfRangeException(nameof(cseq));
        }

        using var stream = new MemoryStream();
        using (var writer = new StreamWriter(stream, Encoding.ASCII, leaveOpen: true))
        {
            writer.NewLine = "\r\n";
            writer.Write("RTSP/1.0 ");
            writer.Write(statusCode.ToString(CultureInfo.InvariantCulture));
            writer.Write(' ');
            writer.Write(reasonPhrase);
            writer.Write("\r\n");
            writer.Write("CSeq: ");
            writer.Write(cseq.ToString(CultureInfo.InvariantCulture));
            writer.Write("\r\n");

            if (headers is not null)
            {
                foreach (var header in headers)
                {
                    ValidateHeader(header);
                    writer.Write(header.Name);
                    writer.Write(": ");
                    writer.Write(header.Value);
                    writer.Write("\r\n");
                }
            }

            writer.Write("Content-Length: ");
            writer.Write(body.Length.ToString(CultureInfo.InvariantCulture));
            writer.Write("\r\n\r\n");
        }

        stream.Write(body);
        return stream.ToArray();
    }

    private static void ValidateHeader(MiPlayRtspHeader header)
    {
        ArgumentNullException.ThrowIfNull(header);
        ArgumentException.ThrowIfNullOrWhiteSpace(header.Name);
        if (header.Name.Contains(':', StringComparison.Ordinal) ||
            header.Name.Contains('\r', StringComparison.Ordinal) ||
            header.Name.Contains('\n', StringComparison.Ordinal))
        {
            throw new ArgumentException("The RTSP header name must be a token without ':' or line breaks.", nameof(header));
        }
        if (header.Name.Equals("CSeq", StringComparison.OrdinalIgnoreCase) ||
            header.Name.Equals("Content-Length", StringComparison.OrdinalIgnoreCase))
        {
            throw new ArgumentException("CSeq and Content-Length are generated by the RTSP response codec.", nameof(header));
        }
        if (header.Value.Contains('\r', StringComparison.Ordinal) ||
            header.Value.Contains('\n', StringComparison.Ordinal))
        {
            throw new ArgumentException("The RTSP header value must be a single line.", nameof(header));
        }
    }
}