namespace DLNACast.Core.MiPlay;

public sealed record MiPlayRealSenderCaptureEndpointSnapshot(
    string RequestedSourceEndpoint,
    string AnalyzerHostAddressObservedByIpconfig,
    string CaptureFilter,
    string SenderToReceiverCaptureFilter,
    string ReceiverToSenderCaptureFilter,
    bool CaptureBytesAvailable,
    bool OfflineDecoderAvailable,
    bool SendsPackets,
    bool ReplaysPackets,
    bool LocalWifiUnicastMayBeInvisible,
    bool RequiresPcapOrTcpPayloadBytes);

public sealed record MiPlayRealSenderCaptureArtifactRequirement(
    string ArtifactKind,
    string MinimumContent,
    bool ContainsReplayableSecretOrMedia,
    string Reason);

/// <summary>
/// Boundary evidence for using an official sender capture as the next MiPlay
/// oracle. The endpoint is intentionally modeled as a capture source, not as a
/// target for generated protocol packets.
/// </summary>
public static class MiPlayRealSenderCaptureEndpointEvidence
{
    public const string RequestedSourceEndpoint = "192.168.10.20:42509";
    public const string SenderAddress = "192.168.10.20";
    public const int SenderPort = 42509;
    public const string AnalyzerHostAddressObservedByIpconfig = "192.168.10.9";
    public const string WiresharkDisplayFilter = "ip.addr == 192.168.10.20 && tcp.port == 42509";
    public const string SenderToReceiverDisplayFilter = "ip.src == 192.168.10.20 && tcp.srcport == 42509";
    public const string ReceiverToSenderDisplayFilter = "ip.dst == 192.168.10.20 && tcp.dstport == 42509";

    public static MiPlayRealSenderCaptureEndpointSnapshot CreateCurrentSnapshot(bool captureBytesAvailable = false) =>
        new(
            RequestedSourceEndpoint,
            AnalyzerHostAddressObservedByIpconfig,
            WiresharkDisplayFilter,
            SenderToReceiverDisplayFilter,
            ReceiverToSenderDisplayFilter,
            captureBytesAvailable,
            OfflineDecoderAvailable: true,
            SendsPackets: false,
            ReplaysPackets: false,
            LocalWifiUnicastMayBeInvisible: true,
            RequiresPcapOrTcpPayloadBytes: !captureBytesAvailable);

    public static IReadOnlyList<MiPlayRealSenderCaptureArtifactRequirement> CreateArtifactRequirements() =>
        [
            new(
                "pcapng-or-pcap",
                "A capture filtered to the official sender endpoint and the S12 control connection, with TCP payload bytes intact.",
                ContainsReplayableSecretOrMedia: true,
                "The byte-level SafetyData command sequence must come from the official sender, but the artifact must remain offline-only because it can contain authentication/session material."),
            new(
                "tcp-payload-hex",
                "Direction-preserving TCP payload streams exported from the capture, preferably 192.168.10.20:42509-to-speaker:8899 and speaker:8899-to-192.168.10.20:42509 as separate hex blobs.",
                ContainsReplayableSecretOrMedia: true,
                "The offline decoder can split '$' command frames and summarize SafetyData headers without requiring live network access."),
        ];

    public static MiPlayIdmStateDecision EvaluateOfflineCaptureBoundary(
        MiPlayRealSenderCaptureEndpointSnapshot snapshot)
    {
        if (snapshot.SendsPackets || snapshot.ReplaysPackets)
        {
            return new MiPlayIdmStateDecision(false, "Real-sender capture evidence must be consumed offline only; generated, replayed, or guessed packets are outside this boundary.");
        }

        if (!snapshot.OfflineDecoderAvailable)
        {
            return new MiPlayIdmStateDecision(false, "No offline command-stream decoder is available for captured TCP payload bytes.");
        }

        if (snapshot.CaptureBytesAvailable)
        {
            return new MiPlayIdmStateDecision(true, "Captured real-sender TCP payload bytes can be decoded offline into MiPlay command-frame summaries and compared against Probe-generated bytes.");
        }

        return new MiPlayIdmStateDecision(
            false,
            "The endpoint 192.168.10.20:42509 is a capture filter/source, not enough evidence by itself; provide pcap/pcapng or exported TCP payload hex before byte-level comparison.");
    }

    public static MiPlayIdmStateDecision EvaluateLocalCaptureVisibility(
        MiPlayRealSenderCaptureEndpointSnapshot snapshot)
    {
        if (!snapshot.LocalWifiUnicastMayBeInvisible)
        {
            return new MiPlayIdmStateDecision(true, "The capture point is expected to see the official sender unicast flow.");
        }

        return new MiPlayIdmStateDecision(
            false,
            $"The analyzer host was observed as {snapshot.AnalyzerHostAddressObservedByIpconfig}, while the official sender endpoint is {snapshot.RequestedSourceEndpoint}; on ordinary Wi-Fi, this host may not see phone-to-speaker unicast unless capture runs on the sender, the speaker/AP/router, monitor mode, or a mirrored path.");
    }
}



